export const TICKET_EVENT = {
  TICKET_CREATED: 'TICKET_CREATED',
  TICKET_ARCHIVED: 'TICKET_ARCHIVED',
  TICKET_CLOSED: 'TICKET_CLOSED',
  TICKET_ASSIGNED: 'TICKET_ASSIGNED',
};

export const CONVERSATION_EVENT = {
  CONVERSATION_RATED: 'CONVERSATION_RATED',
  CONVERSATION_CREATED: 'CONVERSATION_CREATED',
  CONVERSATION_MEMBER_JOINED: 'CONVERSATION_MEMBER_JOINED',
  CONVERSATION_MEMBER_LEFT: 'CONVERSATION_MEMBER_LEFT',
};
